# Generated by Django 5.1 on 2024-11-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='restaurant',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
